;;; ================== TESTING =========================

;;; Load test file
;;; (trace tester) or not 
;;; (tester tests)

(defmatch run-a-test ((?n - ?call => ?result))
  (unless (equal #?result (eval #?call))
    (pprint (match>> '(failed test. ?n -- ?call)))))

(defun tester (tests)
  (mapcar #'run-a-test tests)
  'tests-completed-all-passed)

(defparameter tests

;;;TESTING SIMPLE SENTENCES
      
;;;SHE WENT TO THE GYM      

'((test1 - (parse 'sentence '(she went to the gym)) =>

_____________ 
COMPLETE-EDGE 0 5 S2 SENTENCE (SHE WENT TO THE GYM) NIL
S2   SENTENCE -> (PRONOUN-PHRASE NOUN-PHRASE)
Syntax
(SENTENCE (PRONOUN-PHRASE (PRONOUN SHE) (VERB WENT))
 (NOUN-PHRASE (PREPO TO) (DETERMINER THE) (NOUN GYM)))
Semantics
(SENTENCE (ACTOR SINGULAR FEMALE) (ACTION TRAVEL PAST-TENSE)
 (OBJECT SPECIFIC SINGULAR PLACE))
T
)

;;;HE BURNED THE MEAL

(test2 - (parse 'sentence '(he burned the meal)) => 
                
_____________ 
COMPLETE-EDGE 0 4 S2 SENTENCE (HE BURNED THE MEAL) NIL
S2   SENTENCE -> (PRONOUN-PHRASE NOUN-PHRASE)
Syntax
(SENTENCE (PRONOUN-PHRASE (PRONOUN HE) (VERB BURNED))
 (NOUN-PHRASE (DETERMINER THE) (NOUN MEAL)))
Semantics
(SENTENCE (ACTOR SINGULAR MALE) (ACTION DAMAGE PAST-TENSE)
 (OBJECT SPECIFIC SINGULAR FOOD))
T
)

;;;TESTING COMPLEX SENTENCES

;;;SHE WENT TO THE GYM BECAUSE SHE WANTED TO BECOME HEALTHY

(test3 - (parse 'sentence '(she went to the gym because she wanted to become healthy)) =>
       
_____________ 
COMPLETE-EDGE 0 11 S4 SENTENCE (SHE WENT TO THE GYM BECAUSE SHE WANTED TO BECOME
                                HEALTHY) NIL
S4   SENTENCE -> (SENTENCE ($FIRSTS) CONJU SENTENCE ($SECONDS))
Syntax
(SENTENCE
 (SENTENCE (PRONOUN-PHRASE (PRONOUN SHE) (VERB WENT))
  (NOUN-PHRASE (PREPO TO) (DETERMINER THE) (NOUN GYM)))
 (CONJU BECAUSE)
 (SENTENCE (PRONOUN-PHRASE (PRONOUN SHE) (VERB WANTED))
  (PREPOSITION-PHRASE (PREPO TO)
   (ADJECTIVE-PHRASE (VERB BECOME) (ADJECTIVE HEALTHY)))))
Semantics
(SENTENCE
 ((EFFECT-> (TRAVEL PAST-TENSE) (SPECIFIC SINGULAR PLACE))
  (CAUSE-> ((WANT PAST-TENSE) (CHANGE PRESENT-TENSE)) (GOOD))
  (LINK-> (SEMS . CAUSE))))
T
)

(test4 - (parse 'sentence '(he burned the meal because he forgot it was cooking)) =>

_____________ 
COMPLETE-EDGE 0 10 S10 SENTENCE (HE BURNED THE MEAL BECAUSE HE FORGOT IT WAS COOKING) NIL
S10  SENTENCE -> (SENTENCE ($FIRSTS) CONJU SENTENCE ($SECONDS))
Syntax
(SENTENCE
 (SENTENCE (PRONOUN-PHRASE (PRONOUN HE) (VERB BURNED))
  (NOUN-PHRASE (DETERMINER THE) (NOUN MEAL)))
 (CONJU BECAUSE)
 (SENTENCE (PRONOUN-PHRASE (PRONOUN HE) (VERB FORGOT))
  (VERB-VERB-PHRASE (PRONOUN IT) (VERB WAS) (VERB COOKING))))
Semantics
(SENTENCE (ACTOR MALE SINGULAR)
 ((EFFECT-> (DAMAGE PAST-TENSE) (SPECIFIC SINGULAR FOOD))
  (CAUSE-> ((FORGOT PAST-TENSE) (EXIST PASSIVE) (PREPARE PAST-TENSE)))
  (LINK-> CAUSATION)))
T
)

(test5 - (parse 'sentence '(stop eating bad food in-order to become healthy)) =>

_____________ 
COMPLETE-EDGE 0 8 S9 SENTENCE (STOP EATING BAD FOOD IN-ORDER TO BECOME HEALTHY) NIL
S9   SENTENCE -> (SENTENCE CONJU PREPOSITION-PHRASE)
Syntax
(SENTENCE
 (SENTENCE (VERB-VERB-PHRASE (VERB STOP) (VERB EATING)) (ADJECTIVE BAD) (NOUN FOOD))
 (CONJU IN-ORDER)
 (PREPOSITION-PHRASE (PREPO TO) (ADJECTIVE-PHRASE (VERB BECOME) (ADJECTIVE HEALTHY))))
Semantics
(SENTENCE (ACTOR)
 ((EFFECT-> (END PRESENT-TENSE INGEST CONTINUOUS) ((STATE-BAD) FOOD))
  (CAUSE-> (TO) ((CHANGE) (PRESENT-TENSE)) (HEALTH-GOOD)) (LINK-> (SEMS . CAUSATION))))
T
)

(test6 - (parse 'sentence '(she wanted to become healthy so she went to the gym)) =>

_____________ 
COMPLETE-EDGE 0 11 S10 SENTENCE (SHE WANTED TO BECOME HEALTHY SO SHE WENT TO THE GYM) NIL
S10  SENTENCE -> (SENTENCE ($FIRSTS) CONJU SENTENCE ($SECONDS))
Syntax
(SENTENCE
 (SENTENCE (PRONOUN-PHRASE (PRONOUN SHE) (VERB WANTED))
  (PREPOSITION-PHRASE (PREPO TO) (ADJECTIVE-PHRASE (VERB BECOME) (ADJECTIVE HEALTHY))))
 (CONJU SO)
 (SENTENCE (PRONOUN-PHRASE (PRONOUN SHE) (VERB WENT))
  (NOUN-PHRASE (PREPO TO) (DETERMINER THE) (NOUN GYM))))
Semantics
(SENTENCE (ACTOR FEMALE SINGULAR)
 ((CAUSE-> ((WANT PAST-TENSE) ((CHANGE) (PRESENT-TENSE))) (HEALTH-GOOD))
  (EFFECT-> (TRAVEL PAST-TENSE) (SPECIFIC SINGULAR PLACE)) (LINK-> CAUSING)))
T
)

(test7 - (parse 'sentence '(since she wanted to become healthy she went to the gym)) =>

_____________ 
COMPLETE-EDGE 0 11 S11 SENTENCE (SINCE SHE WANTED TO BECOME HEALTHY SHE WENT TO THE
                                 GYM) NIL
S11  SENTENCE -> (CONJU SENTENCE ($FIRSTS) SENTENCE ($SECONDS))
Syntax
(SENTENCE (CONJU SINCE)
 (SENTENCE (PRONOUN-PHRASE (PRONOUN SHE) (VERB WANTED))
  (PREPOSITION-PHRASE (PREPO TO) (ADJECTIVE-PHRASE (VERB BECOME) (ADJECTIVE HEALTHY))))
 (SENTENCE (PRONOUN-PHRASE (PRONOUN SHE) (VERB WENT))
  (NOUN-PHRASE (PREPO TO) (DETERMINER THE) (NOUN GYM))))
Semantics
(SENTENCE (ACTOR FEMALE SINGULAR)
 ((EFFECT-> (TRAVEL PAST-TENSE) (SPECIFIC SINGULAR PLACE))
  (CAUSE-> ((WANT PAST-TENSE) ((CHANGE) (PRESENT-TENSE))) (HEALTH-GOOD))
  (LINK-> CAUSATION)))
T
)

;(test8 - (parse 'sentence '(john wore a coat because it was cold)) =>
;
;_____________ 
;COMPLETE-EDGE 0 8 S10 SENTENCE (JOHN WORE A COAT BECAUSE IT WAS COLD) NIL
;     Glitches: (GENDER-AGREEMENT)
;S10  SENTENCE -> (SENTENCE ($FIRSTS) CONJU SENTENCE ($SECONDS))
;Syntax
;(SENTENCE
; (SENTENCE (NOUN JOHN)
;  (VERB-PHRASE (VERB WORE) (NOUN-PHRASE (DETERMINER A) (NOUN COAT))))
; (CONJU BECAUSE) (SENTENCE (PRONOUN IT) (ADJECTIVE-PHRASE (VERB WAS) (ADJECTIVE COLD))))
;Semantics
;(SENTENCE (ACTOR MALE SINGULAR)
; ((EFFECT-> (EQUIP) (GENERAL SINGULAR CLOTHES))
;  (CAUSE-> ((EXIST) (PASSIVE)) (TEMPERATURE-LOW)) (LINK-> CAUSATION)))
;T
;)
)
)